from typing import Tuple

CNFLine = Tuple[int, ...]
CNF = Tuple[CNFLine, ...]


def join_cnfs(cnf1: CNF, cnf2: CNF) -> CNF:
    return cnf1 + cnf2


def cnf_to_dimacs(cnf: CNF, header=None) -> str:
    header = """
c
c DIMACS format file generated by SATExpander (https://github.com/PantomInach/SATExpander).
c
""" if header is None else header
    unique_variables = set()
    clauses = ""
    for line in cnf:
        clause_line = ""
        for x in line:
            unique_variables.add(abs(x))
            clause_line += str(x) + " "
        clause_line += "0"
        clauses += clause_line + "\n"
    parameters = f"p cnf {len(unique_variables)} {len(cnf)}"
    return header + parameters + "\n" + clauses
